[package]
name = "ferrous-opengl"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.30.2"
vecmath = "1.0.0"
clock_ticks = "0.1.1"
noise = "0.7.0"
